from alimentos.ext.database import db
from sqlalchemy_serializer import SerializerMixin

calss Alimentos(db.Model, SerializerMix):
    
        id = db.Column(db.Iterger, primary_key=True)
        cd_ibge = db.Column(db.Numeric())
        descricao = db.Column(db.Text())
        cd_md_preparo = db.Column(db.Numeric())
        energia_kcal = db.Column(db.Numeric())
        proteina_g = db.Column(db.Numeric())
        lipidios_totais_g = db.Column(db.Numeric())
        carboidrato_g = db.Column(db.Numeric())
        fibra_alimentar_total_g = db.Column(db.Numeric())
        calcio_mg = db.Column(db.Numeric())
        magnesio_mg = db.Column(db.Numeric())
        manganes_mg = db.Column(db.Numeric())
        foforo_mg = db.Column(db.Numeric())
        ferro_mg = db.Column(db.Numeric())
        sodio_mg = db.Column(db.Numeric())
        sodio_adicao_mg = db.Column(db.Numeric())
        potassio_mg = db.Column(db.Numeric())
        cobre_mg = db.Column(db.Numeric())
        zinco_mg = db.Column(db.Numeric())
        selenio_mcg = db.Column(db.Numeric())
        colesterol_mg = db.Column(db.Numeric())
        ag_saturados_g = db.Column(db.Numeric())
        ag_mono_g = db.Column(db.Numeric())
        ag_poli_g = db.Column(db.Numeric())
        ag_linoleico_g = db.Column(db.Numeric())
        ag_linolenico_g = db.Column(db.Numeric())
        ag_transtotal_g = db.Column(db.Numeric())
        acucar_total_g = db.Column(db.Numeric())
        acucar_adicao_g = db.Column(db.Numeric())
        retinol_mcg = db.Column(db.Numeric())
        vitamina_a_rae_mcg = db.Column(db.Numeric())
        tiamina_mg = db.Column(db.Numeric())
        riboflavina_mg = db.Column(db.Numeric())
        niacina_mg = db.Column(db.Numeric())
        niacina_ne_mg = db.Column(db.Numeric())
        piridoxina_mg = db.Column(db.Numeric())
        cabolamina_mcg = db.Column(db.Numeric())
        folato_dfe_mcg = db.Column(db.Numeric())
        vitamina_d_mg = db.Column(db.Numeric())
        vitamina_e_mg = db.Column(db.Numeric())
        vitamina_c_mg = db.Column(db.Numeric())
        created_at = db.Column(db.DateTime())
        updated_at = db.Column(db.DateTime())